CREATE TABLE PROJETO (ID BIGINT NOT NULL, NOME VARCHAR(255), USUARIO_ID BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE USUARIO (ID BIGINT NOT NULL, NOMECOMPLETO VARCHAR(255), EMAIL VARCHAR(255), SENHA VARCHAR(255), TELEFONE VARCHAR(255), NASCIMENTO DATE, ENDERECO VARCHAR(255), CAIXAPOSTAL VARCHAR(255), CIDADE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE FICHEIRO (ID BIGINT NOT NULL, CAMINHO VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE TAG (ID BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE IMAGEM (ID BIGINT NOT NULL, CAMINHO VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE COMENTARIO (ID BIGINT NOT NULL, TEXTO VARCHAR(255), HORA DATE, PROJETO_ID BIGINT NOT NULL, USUARIO_ID BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE VERSAOPROJETO (ID BIGINT NOT NULL, DESCRICAO VARCHAR(255), PROJETO_ID BIGINT NOT NULL, USUARIO_ID BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE COMPONENTE (ID BIGINT NOT NULL, CONTEUDO VARCHAR(255), TIPO_ID VARCHAR(255), VERSAO_ID BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE TIPO (ID VARCHAR(255) NOT NULL, PRIMARY KEY (ID));

-- Multiple for multiple relationship
CREATE TABLE PROJETO_USUARIO (PROJETO_ID BIGINT NOT NULL, USUARIO_ID BIGINT NOT NULL, PRIMARY KEY (PROJETO_ID, USUARIO_ID));
CREATE TABLE FICHEIRO_TAG (FICHEIRO_ID BIGINT NOT NULL, TAG_ID BIGINT NOT NULL, PRIMARY KEY (FICHEIRO_ID, TAG_ID));

-- Foreign keys
ALTER TABLE PROJETO ADD CONSTRAINT FK_PROJETO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);
ALTER TABLE VERSAOPROJETO ADD CONSTRAINT FK_VERSAOPROJETO_PROJETO FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (ID);
ALTER TABLE VERSAOPROJETO ADD CONSTRAINT FK_VERSAOPROJETO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_PROJETO FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (ID);
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);
ALTER TABLE COMPONENTE ADD CONSTRAINT FK_COMPONENTE_TIPO FOREIGN KEY (TIPO_ID) REFERENCES TIPO (ID);
ALTER TABLE COMPONENTE ADD CONSTRAINT FK_COMPONENTE_VERSAOPROJETO FOREIGN KEY (VERSAO_ID) REFERENCES VERSAOPROJETO (ID);

INSERT INTO USUARIO values(1, 'Eduardo Morais','eduardo@fe.up.pt', '1234', '937333333', '1994-05-12', 'Rua da Ribeira', '209990-99', 'Porto');

INSERT INTO TIPO values('ELETRONICO');
INSERT INTO TIPO values('INFORMATICA');
INSERT INTO TIPO values('OUTROS');