CREATE TABLE PROJETO (ID BIGINT NOT NULL, NOME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE USUARIO (ID BIGINT NOT NULL, NOMECOMPLETO VARCHAR(255), EMAIL VARCHAR(255), SENHA VARCHAR(255), TELEFONE VARCHAR(255), NASCIMENTO DATE, ENDERECO VARCHAR(255), CAIXAPOSTAL VARCHAR(255), CIDADE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE FICHEIRO (ID BIGINT NOT NULL, CAMINHO VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE IMAGEM (ID BIGINT NOT NULL, CAMINHO VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE COMENTARIO (ID BIGINT NOT NULL, TEXTO VARCHAR(255), HORA DATE, ID_PROJETO BIGINT NOT NULL, PRIMARY KEY (ID));
CREATE TABLE VERSAOPROJETO (VERSAO BIGINT NOT NULL, DESCRICAO VARCHAR(255), PRIMARY KEY (VERSAO));
CREATE TABLE COMPONENTE (ID BIGINT NOT NULL, TIPO VARCHAR(255), CONTEUDO VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE TIPO (ID VARCHAR(255) NOT NULL, PRIMARY KEY (ID));

ALTER TABLE COMPONENTE ADD CONSTRAINT FK_COMPONENTE_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO (ID);
ALTER TABLE COMENTARIO ADD CONSTRAINT FK_COMENTARIO_PROJETO FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO (ID);

INSERT INTO USUARIO values(1, 'Eduardo Morais','eduardo@fe.up.pt', '1234', '937333333', '1994-05-12', 'Rua da Ribeira', '209990-99', 'Porto');

INSERT INTO TIPO values('ELETRONICO');
INSERT INTO TIPO values('INFORMATICA');
INSERT INTO TIPO values('OUTROS');

