ALTER TABLE COMPONENTE DROP CONSTRAINT FK_COMPONENTE_TIPO;
ALTER TABLE COMENTARIO DROP CONSTRAINT FK_COMENTARIO_PROJETO;

DROP TABLE PROJETO;
DROP TABLE USUARIO;
DROP TABLE FICHEIRO;
DROP TABLE IMAGEM;
DROP TABLE COMENTARIO;
DROP TABLE VERSAOPROJETO;
DROP TABLE COMPONENTE;
DROP TABLE TIPO;