ALTER TABLE PROJETO DROP CONSTRAINT FK_PROJETO_USUARIO;
ALTER TABLE VERSAOPROJETO DROP CONSTRAINT FK_VERSAOPROJETO_PROJETO;
ALTER TABLE VERSAOPROJETO DROP CONSTRAINT FK_VERSAOPROJETO_USUARIO;
ALTER TABLE COMENTARIO DROP CONSTRAINT FK_COMENTARIO_PROJETO;
ALTER TABLE COMENTARIO DROP CONSTRAINT FK_COMENTARIO_USUARIO;
ALTER TABLE COMPONENTE DROP CONSTRAINT FK_COMPONENTE_TIPO;
ALTER TABLE COMPONENTE DROP CONSTRAINT FK_COMPONENTE_VERSAOPROJETO;

DROP TABLE PROJETO;
DROP TABLE USUARIO;
DROP TABLE FICHEIRO;
DROP TABLE TAG;
DROP TABLE IMAGEM;
DROP TABLE COMENTARIO;
DROP TABLE VERSAOPROJETO;
DROP TABLE COMPONENTE;
DROP TABLE TIPO;

DROP TABLE PROJETO_USUARIO;
DROP TABLE FICHEIRO_TAG;